defaults:
  - /path: __task__
  - /module: __init__

_config_name_: __init__
project: ${oc.select:project,null}
task_name: __init__
task_root: ${oc.select:project.path.project_workspace_root,workspace}
autoload: false
version: ${__version__:}
verbose: ${oc.select:project.verbose,false}
pipelines:
