defaults:
  - /path: __task__
  - /module: __init__

_config_group_: /task
_config_name_: __init__
task_name: ${._config_name_}
task_root: ${oc.select:project.project_root,.}/${oc.select:project.project_workspace_name,workspace}
version: ${__version__:}
verbose: ${oc.select:project.verbose,false}
pipelines:
