defaults:
  - /path: __task__
  - /module: __init__
  - /pipeline@pipeline:
      - __init__

_config_name_: __init__
project: ${oc.select:project,null}
task_name: demo-task
task_root: ${oc.select:project.path.project_workspace_root,workspace/tasks}
autoload: false
version: ${__version__:}
verbose: ${oc.select:project.verbose,false}
pipelines:
  - pipeline
