defaults:
  - /path: __task__
  - /module: __init__
  - /pipeline@pipeline:
      - __init__

project: ${oc.select:project,null}
task_name: demo-task
task_root: ${oc.select:project.path.project_workspace_root,workspace/tasks}/${.task_name}
autoload: false
version: "0.0.0"
pipelines:
  - pipeline
