defaults:
  - /path: __task__
  - /module: __init__
  - /pipeline@pipeline1: __test_general__
  - /pipeline@pipeline2: __test_dataframe__

_config_name_: __test__
project: ${oc.select:project,null}
task_name: demo-task
task_root: ${oc.select:project.path.project_workspace_root,workspace/tasks}/${.task_name}
autoload: false
verbose: true
pipelines:
  - pipeline1
  - pipeline2
