[tool.poe.tasks.install-ipython]
cmd = "poetry install --with ipython"
help = "install ipython dependencies"

[tool.poe.tasks.install-mkdocs]
cmd = "poetry install --with mkdocs"
help = "install mkdocs dependencies"

[tool.poe.tasks.build-docs]
cmd = "mkdocs build"
help = "build documentation"
