# When modifying this file, please validate using
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate
coverage:
  status:
    project:
      default:
        target: 30% # the required coverage value
        threshold: 10% # the leniency in hitting the target
        informational: true
    patch:
      default:
        informational: true
