_target_: hyfi.utils.datasets.slice.DSSlice.filter_and_sample_data
queries: null
sample_size: null
sample_seed: 42
output_dir: .
sample_filename: null
train_filename: train.parquet
discard_filename: null
returning_data: train
verbose: false
