defaults:
- /path@path: __batch__
- /batch@batch: __init__
- /run@load_args: load_data
_target_: hyfi.runner.base.TestRunner
_config_name_: __test__
_config_group_: /runner
verbose: false
task_name: demo-task
task_root: workspace
version: 0.0.0
module: null
pipelines: []
batch_name: demo
calls: []
