defaults:
  - __init__

_target_: hyfi.main.HyFI.load_dataframes
data_files:
data_dir:
filetype:
split:
concatenate: false
ignore_index: false
use_cached: false
verbose: ${oc.select:..verbose, false}
