---
name: deploy-docs
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - release
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - "README.md"
      - "mkdocs.yaml"
      - "docs/**.md"
      - "docs/images/**"
      - ".github/workflows/deploy-docs.yaml"
      - "src/**"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # set up python
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      # install the source code
      - name: Install the source code
        run: pip install .

      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          pip install -r docs/requirements.txt
          mkdocs gh-deploy --force
